### PR TITLE
add: publication section

### PR DESCRIPTION
**Pull request by Gorgeous-Patrick**
This PR adds a publication section on the index page. I think this section is important for many researcher coders.

### CODE REVIEW

**Comment by Gorgeous-Patrick** [comment]
I am sorry.. I found myself not exactly good at frontend.. If you find anything wrong or implemented incorrectly.. please tell me. Thank you!

**Comment by samrobbins85** [comment]
Thanks @Gorgeous-Patrick, this looks like a great addition, I made a couple changes and I've put it on a branch of this repo in https://github.com/samrobbins85/hugo-developer-portfolio/tree/Patrick-Publications, can you give it a look and see if there's any changes you think I shouldn't have made. 

Summary of the changes:
- Change the key from `publication` to `publications`
- Change the title from Publication to Publications
- Fix the height of images so they don't end up looking too large
- Change academy from `h4` to `span`, removing some of the top padding that looked strange
- Remove spacing in the code

**Comment by Gorgeous-Patrick** [comment]
I have compiled it locally and it looks perfect to me. Thank you!

**Comment by Gorgeous-Patrick** [comment]
Plus, I have added some documentation to the readme file.

**Pull request merged**
